# Generated by Django 6.0.5 on 2026-05-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isp_name', models.CharField(default='NetFlow Broadband Ltd.', max_length=120)),
                ('support_phone', models.CharField(default='+92 42 111-638-356', max_length=40)),
                ('support_email', models.EmailField(default='support@netflow.com.pk', max_length=254)),
                ('currency', models.CharField(default='PKR', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=16.0, max_digits=5)),
                ('late_fee', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('billing_day', models.IntegerField(default=5)),
                ('ai_model', models.CharField(default='gemini-1.5-flash', max_length=80)),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('auto_prioritize', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_settings',
            },
        ),
    ]
